_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 337fa836-4d3c-4d4f-9e55-fb7cc0eb15da
name: cidemo-rannel-d9
mail: john.valdez@pantheon.io
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
